receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ":4317"
      http:
        endpoint: ":55681"

exporters:
  otlp:
    endpoint: "localhost:14250"  # Jaeger's gRPC collector port
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
