

#version: '3.7'
#services:
#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "16686:16686" # the jaeger UI
#      - "4317:4317" # the OpenTelemetry collector grpc
#    environment:
#      - COLLECTOR_OTLP_ENABLED=true

# docker-compose up -d